# Generated by Django 4.0.4 on 2022-05-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_price_alter_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='contInStock',
            new_name='countInStock',
        ),
    ]
