# Generated by Django 4.0.4 on 2022-05-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_continstock_product_countinstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='taxPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
