# Generated by Django 4.0.4 on 2022-05-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_order_taxprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='aprt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
